
import ParticlesWrapper from "./_components/ParticlesWrapper"
import type { Metadata } from "next";
import { Comfortaa } from "next/font/google"
import "./globals.css";


const comfortaa = Comfortaa({
    subsets: ["latin", "cyrillic"],
    weight: ["300", "400", "500"]
});


export default function RootLayout({
    children
}: {
    children: React.ReactNode
}){
    return (
        <html lang="ru" className="bg-white dark:bg-black text-black dark:text-slate-100 ">
            <body className={`${comfortaa.className} antialiased`}>
                <ParticlesWrapper>
                    {children}
                    
                </ParticlesWrapper>
            </body>
        </html>
    )
}



export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};